apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xat5g2gra-python 
  janus-idp.io/tekton: xat5g2gra-python
  backstage.io/kubernetes-id: xat5g2gra-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xat5g2gra-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  