apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xat5g2gra-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xat5g2gra-python 
  name: xat5g2gra-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xat5g2gra-python 
